# Generated by Django 4.2.23 on 2025-08-09 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=50)),
                ('account_id', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=200)),
                ('api_secret', models.CharField(max_length=200)),
                ('access_token', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TradeMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(max_length=100, unique=True)),
                ('instrument', models.CharField(max_length=20)),
                ('ce_strike', models.IntegerField()),
                ('pe_strike', models.IntegerField()),
                ('expiry', models.CharField(max_length=15)),
                ('initial_premium', models.FloatField()),
                ('target_amount', models.FloatField()),
                ('stoploss_amount', models.FloatField()),
                ('status', models.CharField(default='Running', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('final_pnl', models.FloatField(blank=True, null=True)),
                ('entry_tag', models.CharField(default='General', max_length=100)),
                ('auto_close_target', models.BooleanField(default=True)),
                ('auto_close_stoploss', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PnLHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_premium', models.FloatField()),
                ('pnl', models.FloatField()),
                ('ce_price', models.FloatField(default=0)),
                ('pe_price', models.FloatField(default=0)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnl_history', to='analyzer.trademonitor')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AutomationStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instrument', models.CharField(max_length=20)),
                ('strategy_type', models.CharField(max_length=50)),
                ('schedule_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('broker_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analyzer.brokeraccount')),
            ],
        ),
    ]
