# Generated by Django 4.2.23 on 2025-08-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnlhistory',
            name='trade',
        ),
        migrations.DeleteModel(
            name='AutomationStrategy',
        ),
        migrations.DeleteModel(
            name='BrokerAccount',
        ),
        migrations.DeleteModel(
            name='PnLHistory',
        ),
        migrations.DeleteModel(
            name='TradeMonitor',
        ),
    ]
